### ISSUE TITLE
Todo from game.php

### ISSUE THREAD

**Issue by reggi** [IanGallacher/LearnToCode#1]
* [ ] write more defensive code. 
* [ ] add white tile grid so screen can redraw / white canvas image. 
* [ ] valid level checking.
* [ ] valid html markup. No duplicate ID's, etc
* [ ] for loop sizing.
* [ ] defensive code for maps. Currently, I believe the code I have to be broken.  
* [ ] remove php entirely from the equation.
